# Generated by Django 3.1.2 on 2020-12-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactos',
            new_name='Contacto',
        ),
    ]
