# Generated by Django 3.1.2 on 2020-12-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_auto_20201213_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Contactos',
        ),
    ]
