# Generated by Django 3.1.2 on 2020-12-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_auto_20201213_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
