# Generated by Django 3.1.2 on 2020-11-09 01:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planesmovil', '0002_auto_20201108_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planmovil',
            new_name='Plan_movil',
        ),
    ]
